name: ${PROJECT_NAME}
services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /workspace
    tty: true
    stdin_open: true
    env_file:
      - .env
